### PR TITLE
Create a.js

### PR DESCRIPTION
**Pull request by fnenu**
[Review on Reviewable](https://reviewable.io/reviews/fnenu/things/2)

### CODE REVIEW

**Comment by fnenu** [comment]
<sup>**[a.js, line 1 [r1]](https://reviewable.io:443/reviews/fnenu/things/2#-JoVoiLiytb9vRf1oJrm)** ([raw file](https://github.com/fnenu/things/blob/a0278c1cb98d325f42e93cc48cb58ca237f40898/a.js#L1)):</sup>
hello this is a comment.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fnenu/things/2)

**Comment by fnenu** [comment]
<sup>**[a.js, line 1 [r1]](https://reviewable-dev-fnenu.firebaseapp.com:443/reviews/fnenu/things/2#-JpEXuwpytGLxzHTFUSV)** ([raw file](https://github.com/fnenu/things/blob/a0278c1cb98d325f42e93cc48cb58ca237f40898/a.js#L1)):</sup>
a comment :hear_no_evil: 

---

Comments from the [review on Reviewable.io](https://reviewable-dev-fnenu.firebaseapp.com:443/reviews/fnenu/things/2)

**Comment by fnenu** [comment]
Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- a.js @ r1

---

<sup>**[a.js, line 1 [r1]](https://localhost:8080/reviews/fnenu/things/2#-JpEXuwpytGLxzHTFUSV)** ([raw file](https://github.com/fnenu/things/blob/a0278c1cb98d325f42e93cc48cb58ca237f40898/a.js#L1)):</sup>
:see_no_evil: 

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenu/things/2)

**Comment by fnenu** [comment]
Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- a.js @ r1

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenu/things/2)

**Comment by fnenuwnar** [comment]
hmmm

---

Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/fnenu/things/2)

**Pull request merged**
